name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # ඔබට අවශ්‍ය ඕනෑම වෙලාවක manual එකක් රන් කිරීමට

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22' # අවශ්‍ය පැකේජ සඳහා 22 භාවිතා කරන්න

    - name: Install dependencies
      run: npm install

    - name: Run Bot
      env:
        SESSION_ID: ${{ secrets.SESSION_ID }}
        PORT: ${{ secrets.PORT }}
      run: |
        # බොට් එක දිගටම ක්‍රියාත්මක වීමට node index.js යොදන්න
        # ඔබේ ප්‍රධාන ෆයිල් එකේ නම index.js නම් එය එසේම තබන්න
        node index.js &
        sleep 10
